AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS notify Slack application.
Resources:
  NotifySlackFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bin/main
      Runtime: go1.x
      Environment:
        Variables:
          SLACK_HOOK: https://hooks.slack.com/services/...